# Generated by Django 4.2.6 on 2023-10-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=40, unique=True)),
                ('event_Type', models.CharField(choices=[('F', 'FLORECIMIENTO'), ('O', 'ORGANIZACIONAL')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password1', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=45)),
                ('password2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('personType', models.CharField(choices=[('N', 'NATURAL'), ('J', 'JURIDICA')], max_length=1)),
                ('contact_number', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200)),
                ('previousColab', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.CharField(max_length=100)),
                ('Sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmModule.sponsor')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmModule.event')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('officiaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmModule.official')),
                ('sponsorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmModule.sponsor')),
            ],
        ),
    ]
