# Generated by Django 4.2.5 on 2023-09-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='contact_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='personType',
            field=models.CharField(max_length=200),
        ),
    ]
