# Generated by Django 4.2.6 on 2023-10-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmModule', '0002_remove_sponsor_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='officiaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmModule.official'),
        ),
    ]
