# Generated by Django 4.2.5 on 2023-10-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmModule', '0003_alter_sponsor_persontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_Type',
            field=models.CharField(choices=[('F', 'FLORECIMIENTO'), ('O', 'ORGANIZACIONAL')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Event_Type',
        ),
    ]
