# Generated by Django 3.1.3 on 2023-10-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmModule', '0004_auto_20231002_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='sponsorId',
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.FileField(null=True, upload_to='agreements_pdf/'),
        ),
    ]
