# Generated by Django 3.1.3 on 2023-10-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmModule', '0005_auto_20231007_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='report',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='uploadedFile',
            field=models.FileField(default='pred', upload_to='Uploaded Files/'),
        ),
    ]
