# Generated by Django 3.1.3 on 2023-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmModule', '0006_auto_20231008_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
    ]
